server:
  port: 8080
spring:
  application:
    name: "GeolocalizacionIps"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer-ipapi:
    timeout: 5000
    url: "http://api.ipapi.com"
    access-key: "a293e059a7f8b6ce3461fa1e3f3c0f46"
  restconsumer-rates:
    timeout: 5000
    url: "https://openexchangerates.org"
    app-id: "2f699d0496654411abcf3410b81f9038"
  restconsumer-timezone:
    timeout: 5000
    url: "https://restcountries.com"
datasource:
  r2dbc:
    host: "localhost"
    port: 3306
    username: "root"
    password: "root"
msgbroker:
  host: "localhost"
  password: "guest"
  username: "guest"
resilience4j:
  circuitbreaker:
    instances:
      restConsumer:
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
        failureRateThreshold: 50
logging:
  level:
    org:
      springframework:
        cache: TRACE
